title: The Starscape Archives Political Chart
description: by miiiiiilaaaan
theme: minima
minima:
  social_links:
    - title: TSA Discord server
      icon: fa-github
      url: "https://discord.gg/GV85V9AFw8"
  custom_css:
    - assets/css/dark-mode.css

