title: The Starscape Archives Political Chart
description: >- 
  A description of your site.

theme: minima
minima:
  skin: dark
  custom_css:
    - assets/css/dark-mode.css
  social_links:
    - title: TSA Discord server
      icon: github
      url: "https://discord.gg/GV85V9AFw8"
