title: The Starscape Archives Political Chart
name: PoliticalChart
description: >- 
  The official TSA Political Chart. 
remote_theme: jekyll/minima
minima: dark
plugins:
  - jekyll-remote-theme
github_username: miiiiiilaaaan
email: (https://discord.gg/GV85V9AFw8)
