title: The Starscape Archives Political Chart
name: PoliticalChart
description: >- 

theme: minima
minima:
  skin: dark
  custom_css:
    - assets/css/dark-mode.css

social_links:
 - title: TSA Discord server
     icon: fa-discord
     url: "https://discord.gg/GV85V9AFw8"
